### ISSUE TITLE
sync xhr not supported by XHook (Bootstrap)

### ISSUE THREAD

**Issue by rafaelfernandezgis** [jpillora/xdomain#90] opened 2014-07-02 14:51 UTC
I am using your XDOMAIN code in my project. I have published a web service:
http://map.stjohns.ca/CSJMSGovernWebServiceDMZ/CSJMSGovernWebServiceDMZ.asmx

And I am consuming it using AJAX.
The initial stage of this project is only getting street names from an autocomplete text box (right-top). You can see it here (you can type Water St.):
http://jsfiddle.net/nuR8G/embedded/result/

In this project, I am using JQuery mobile and as far as you can see, the XDOMAIN code works pretty well. The application is communicated with the server and this returns right results.

But this application is not only for mobile devices, it is even for desktop use. For this reason I am trying to forget to JQuery Mobile and I started to use a twitter Bootstrap template since it has more flexibility. However, I am getting the next error from the XDOMAIN code:
xhook is not defined (xdomain.min.js)

You can see it here:
http://jsfiddle.net/hLp8P/5/

Please, do you have any clue about the reason that XDOMAIN is not working on a Bootstrap template?

Thanks for your time and congrats for your code!!

**Comment by rafaelfernandezgis** [comment] 2014-07-03 16:34
Looking for the forums, I found the problem. You need adding this line:
window.xhook = xhook;

after:
xhook = EventEmitter(true);
and before:
xhook.EventEmitter = EventEmitter;

Hopefully it helps somebody else.

Cheers,
Rafael

**Comment by jpillora** [comment] 2014-07-13 11:14
Hi Rafael, sorry for the late reply. This seems to be caused by requirejs/amd. Will close this and track this bug on #91

**Closed as completed by jpillora** 2014-07-13 11:14 UTC

**Comment by jpillora** [comment] 2014-07-13 14:07
This should be fixed now, see http://jpillora.com/xdomain/example/requirejs/
