### ISSUE TITLE
Crashes browser tab when under heavy load.

### ISSUE THREAD

**Issue by ghost** [jpillora/xdomain#10] opened 2013-09-11 11:21 UTC
Apologies for this being a vague issue report, I am trying to nail down the exact cause and test case. I have a large-ish single page app, and at times (usually after the source has been rebuilt and the browser is loading fresh js files) when xdomain is making several request it will cause the browser tab to hang, in a memory leak sort of fashion. The tab never recovers and has to be closed. 
I have noticed this in latest Chrome & Chrome Canary on Mac OSX 10.8.4

**Comment by jpillora** [comment] 2013-09-11 11:24
Interesting, could you possibly replicate this, somewhere which is publicly accessible?

**Comment by jpillora** [comment] 2013-09-11 11:29
There were many changes in `v0.5.0`, have you tried upgrading? or maybe your'e using `v0.4.x` and I've introduced a bug? [Down,Up]grade and let me know how that goes

**Comment by ghost** [comment] 2013-09-11 11:31
I am trying to create a test case but it is tricky because of the setup required.

One thing I have seen just before the tab goes full unresponsive is 1000's of console logs saying..

> Timeout connecting to Iframe: http://xyz.domain.com

**Comment by jpillora** [comment] 2013-09-11 11:32
Ahh a loop...

**Comment by jpillora** [comment] 2013-09-11 12:49
So,

> Timeout connecting to Iframe: http://xyz.domain.com

isn't the actual error right? you've setup your own domains? 

Re - My comment above: What version are you using?

**Comment by ghost** [comment] 2013-09-11 12:52
I was using 0.4 but just pulled the latest and the issue still exists. The 'ready' variable never gets set to true as far as I can tell, and the knock-on effect is that readyCheck() runs repeatedly.
Its seems to happen when the server is not immediately available. i.e. if i recycle the server service and it is taking a moment to spin up.

**Comment by jpillora** [comment] 2013-09-11 13:05
Just pushed a new `0.5`, it's not a bug with `readyCheck`, somewhere must be attempting to send repeatedly, I think. I've added a few more error checks, however the problem of why it's not detecting the slave iframe is still unknown... What ajax library are you using? Maybe you could test it with JSFiddle and public Dropbox?

Will check back on this tomorrow :)

**Comment by ghost** [comment] 2013-09-11 14:24
I think that last commit broke something! Might want to revert :)

I'm using Angular's $http (1.2.0 rc2)

**Comment by jpillora** [comment] 2013-09-11 14:33
Are you getting different results now?

It's not possible to demonstrate your setup?

Will test new angular tomorrow, demos still work for me...

**Comment by ghost** [comment] 2013-09-11 14:36
In this latest commit, I get errors suggesting that the XHR request is no longer getting wrapped. This looks like an issue in the latest commit. I am trying to setup a demonstration of the isssue - will let you know.

**Comment by jpillora** [comment] 2013-09-11 14:38
I only added two lines...

What are the errors?

Do the demos work?

**Comment by ghost** [comment] 2013-09-11 14:45
No, the demos dont work.

> XMLHttpRequest cannot load http://echo.jpillora.com/foo-bar. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:4000' is therefore not allowed access.

**Comment by jpillora** [comment] 2013-09-11 14:48
Caching issue?
Try with Firefox maybe? I'm only on my phone atm though its working in both
chrome and safari

**Comment by jpillora** [comment] 2013-09-11 14:54
Ahhh I wasn't seeing it due to the latency on the phone, should be fixed now

**Comment by ghost** [comment] 2013-09-11 15:43
I have managed to simulate the basic issue, but only locally. I have committed an example of the issue to my fork - https://github.com/DveMac/xdomain.
Instructions are in ./example/slowserver/README.txt

You should see ~8 Timeout errors in the console.log.

**Comment by jpillora** [comment] 2013-09-11 15:51
nearly fixed...

**Closed as completed** 2013-09-11 15:54 UTC

**Comment by jpillora** [comment] 2013-09-11 15:56
Okay finally found the bugs

Added two new examples:

http://jpillora.com/xdomain/example/angular/
http://jpillora.com/xdomain/example/performance/

Really need a test suite!

Thanks for the demo

**Comment by ghost** [comment] 2013-09-11 16:04
> Really need a test suite!

I say this daily!

That looks good to me. works in my demo and the actual app. Thanks! :)

**Comment by jpillora** [comment] 2013-09-11 16:40
No worries

Yeah, I was trying to get testling CI working, since its free for open source and it would test ALL the browsers, and i was getting issues. I can use phantom on travis though thats only webkit, which isnt as useful
